version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
